Controllers/CarrinhoCompraController.cs
using EcommerceMVC.Models;
using EcommerceMVC.Repositories.Interfaces;
using EcommerceMVC.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EcommerceMVC.Controllers {
    public class CarrinhoCompraController : Controller {
        //Injetando a instancia para o acesso dos produtos e o carrinho
        private readonly IProdutoRepository _produtoRepository;
        private readonly CarrinhoCompra _carrinhoCompra;

        public CarrinhoCompraController(IProdutoRepository produtoRepository, CarrinhoCompra carrinhoCompra) {
            _produtoRepository = produtoRepository;
            _carrinhoCompra = carrinhoCompra;
        }

        public IActionResult Index() {
            //Itens a serem obtidos
            var itens = _carrinhoCompra.GetCarrinhoCompraItens();
            _carrinhoCompra.CarrinhoCompraItems = itens;
            //Instancia da ViewModel
            var carrinhoCompraVM = new CarrinhoCompraViewModel {
                CarrinhoCompra = _carrinhoCompra,
                CarrinhoCompraTotal = _carrinhoCompra.GetCarrinhoCompraTotal()
            };
            return View(carrinhoCompraVM);
        }
        [Authorize]
        public RedirectToActionResult AdicionarItemNoCarrinhoCompra(int produtoId) {
            //Retorno do primeiro elemento da sequencia, ou se não existir, um padrão
            var produtoSelecionado = _produtoRepository.Produtos.FirstOrDefault(p => p.ProdutoId == produtoId);
            if (produtoSelecionado != null) {
                _carrinhoCompra.AdicionarAoCarrinho(produtoSelecionado);
            }
            return RedirectToAction("Index");
        }
        [Authorize]
        public RedirectToActionResult RemoverItemNoCarrinhoCompra(int produtoId) {
            //Retorno do primeiro elemento da sequencia, ou se não existir, um padrão
            var produtoSelecionado = _produtoRepository.Produtos.FirstOrDefault(p => p.ProdutoId == produtoId);
            if (produtoSelecionado != null) {
                _carrinhoCompra.RemoverDoCarrinho(produtoSelecionado);
            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/ContatoController.cs
using Microsoft.AspNetCore.Mvc;

namespace EcommerceMVC.Controllers {
    public class ContatoController : Controller {
        public IActionResult Index() {
            return View();
        }
    }
}

Controllers/ProdutoController.cs
using EcommerceMVC.Models;
using EcommerceMVC.Repositories.Interfaces;
using EcommerceMVC.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Runtime.CompilerServices;

namespace EcommerceMVC.Controllers {
    public class ProdutoController : Controller {

        //Injetando acesso ao BD pelo repository
        private readonly IProdutoRepository _produtoRepository;

        public ProdutoController(IProdutoRepository produtoRepository) {
            _produtoRepository = produtoRepository;
        }

        //precisa receber o parametro do nome da categoria
        public IActionResult List(string categoria) {

            //Filtando pela categoria
            IEnumerable<Produto> produtos;
            string categoriaAtual = string.Empty;

            //Retonar tudo
            if (string.IsNullOrEmpty(categoria)) {
                produtos = _produtoRepository.Produtos.OrderBy(l => l.ProdutoId);
                categoriaAtual = "Todos os produtos";
            } else {
                //LEGADO
                /*if (string.Equals("Estoicos", categoria, StringComparison.OrdinalIgnoreCase)) {
                    produtos = _produtoRepository.Produtos.Where(l => l.Categoria.CategoriaNome.Equals("Estoicos")).OrderBy(l => l.Nome);
                } else if (string.Equals("Manga", categoria, StringComparison.OrdinalIgnoreCase)) {
                    produtos = _produtoRepository.Produtos.Where(l => l.Categoria.CategoriaNome.Equals("Manga")).OrderBy(l => l.Nome);
                } else if (string.Equals("Suplementos", categoria, StringComparison.OrdinalIgnoreCase)) {
                    produtos = _produtoRepository.Produtos.Where(l => l.Categoria.CategoriaNome.Equals("Suplementos")).OrderBy(l => l.Nome);
                } else {
                    produtos = _produtoRepository.Produtos.Where(l => l.Categoria.CategoriaNome.Equals("404")).OrderBy(l => l.Nome);}*/

                //Consulta das categorias
                produtos = _produtoRepository.Produtos.Where(l => l.Categoria.CategoriaNome.Equals(categoria)).OrderBy(c => c.Nome);

                categoriaAtual = categoria;
            }
            var produtosListViewModel = new ProdutoListViewModel {
                Produto = produtos,
                CategoriaAtual = categoriaAtual
            };

            return View(produtosListViewModel);
        }

        public IActionResult Details(int produtoId) {
            var produto = _produtoRepository.Produtos.FirstOrDefault(l => l.ProdutoId == produtoId);
            return View(produto);
        }

        //Pesquisar produto pelo nome
        public ViewResult Search(string searchString) {
            IEnumerable<Produto> produtos;
            string categoriaAtual = string.Empty;

            if (string.IsNullOrEmpty(searchString)) {
                produtos = _produtoRepository.Produtos.OrderBy(p => p.ProdutoId);
                categoriaAtual = "Todos os Produtos";
            } else {
                produtos = _produtoRepository.Produtos.Where(p => p.Nome.ToLower().Contains(searchString.ToLower()));
                if (produtos.Any())
                    categoriaAtual = "Produtos";
                else
                    categoriaAtual = "Nenhum produto foi encontrado";
            
            }
            return View("~/Views/Produto/List.cshtml", new ProdutoListViewModel{
                Produto = produtos,
                CategoriaAtual = categoriaAtual
            });
        }
    }
}

Views/Shared/_Carousel.cshtml
<div id="carouselEcommerce" class="carousel slide" data-bs-ride="true">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselEcommerce" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselEcommerce" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselEcommerce" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/img/Carousel/Stoicism/STOICISM.png" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="~/img/Carousel/Manga/BEST MANGAS.png" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="~/img/Carousel/Gym/SUPLEMENTS.png" class="d-block w-100" alt="...">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselEcommerce" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselEcommerce" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EcommerceMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EcommerceMVC.styles.css" asp-append-version="true" />
</head>
<body >
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EcommerceMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1 flex-sm-row-reverse">
                        <li class="nav-item">
                            @await Component.InvokeAsync("CategoriaMenu")
                        </li>
                        <li>
                            <form class="navbar-form navbar-right" asp-controller="Produto" asp-action="Search" method="get" style="margin-right:1px">
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="Procurar Produto" name="searchString" value="@ViewData["searchString"]" />
                                </div>
                            </form>
                        </li>
                        <li class="nav-item">
                            @await Component.InvokeAsync("CarrinhoCompraResumo")
                        </li>
                        <!--<li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                        </li>-->
                        @await Html.PartialAsync("_LoginPartial")
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Contato" asp-action="Index">Contato</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if(User.IsInRole("Admin")){
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Admin" asp-controller="Admin" asp-action="Index">ADMIN</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - EcommerceMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_ProdutosResumo.cshtml
<!--Model para a partial view-->
@model Produto;

<div class="container justify-content-center  row-cols-md-auto">
    <div class="row justify-content-center" style="margin:2px;border: 1px solid #000;border-radius:10px;height:462.8px;">
        @if (Model.ProdutoId != 9) {
            <p class="img-fluid">
                <img class="img-fluid" style="height:270px;width:150px;" src="@Model.ImagemUrl" />
            </p>
        } else {
            <p class="img-fluid">
                <img class="img-fluid" style="height:270px;width:200px;" src="@Model.ImagemUrl" />
            </p>
        }
        <a asp-controller="Produto" asp-action="Details" asp-route-ProdutoId="@Model.ProdutoId">
            @Model.Nome
        </a>
        <h4><strong>Preço: @Model.Preco.ToString("c")</strong></h4>
        <p>@Model.DescricaoCurta</p>
        <div>
            <p class="button">
                <a class="btn btn-primary" id="cartButton" asp-controller="CarrinhoCompra" asp-action="AdicionarItemNoCarrinhoCompra" asp-route-produtoId="@Model.ProdutoId">
                    Incluir no Carrinho
                </a>
            </p>
        </div>
    </div>
</div>